### ISSUE TITLE
VectorTileEncoder constructor throws NoSuchMethodError

### ISSUE THREAD

**Issue by amiskelly** [ElectronicChartCentre/java-vector-tile#9]
The constructor VectorTileEncoder(int, int, boolean) refers to a method GeometryFactory.createPolygon(Coordinate[]) which doesn't appear to exist in the current JTS API.

This results in a NoSuchMethodError when attempting to run with Maven dependencies on a current GeoTools release.

Can you please take a look or clarify the correct set of dependencies?

**Comment by halset** [comment]
What version of JTS are you using? It seem to work fine with 1.13 mentioned in pom.xml and 1.13 is not that old.
